CREATE TABLE tipos_sangre (
    id_tipo_sangre INT PRIMARY KEY AUTO_INCREMENT,
    nombre_tipo_sangre VARCHAR(10) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);