CREATE TABLE niveles_educacion (
    id_nivel_educacion INT PRIMARY KEY AUTO_INCREMENT,
    nombre_nivel_educacion VARCHAR(50) UNIQUE NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);